### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by zero77** [essandess/easylist-pac-privoxy#1]
Wow this is really nice, although can you add support for it to be used with ublock and android ad blockers like below.
github.com/julian-klode/dns66
github.com/AdguardTeam/AdguardForAndroid
github.com/bitbeans/SimpleDnsCrypt    -      Under the filter section 
Thanks

**Comment by essandess** [comment]
Thanks.

This is a network-level blocker, not a client-lever blocker like ublock.

It will block trackers and ad servers on android and iOS and desktop devices alike.

Is there a specific site you don't see in the rule set that should be blocked? Is this site part of the EasyList rules?

**Comment by regsgood** [comment]
Hi, great!
Could you integrate the german Easylist-Filter from here?
https://easylist.to/easylistgermany/easylistgermany.txt

Would be great to select whitch easylist-filter(s) should be integreated.

**Comment by essandess** [comment]
I'm refactoring the entire script to allow greater flexibility in limiting rules and the resulting proxy.pac file size/complexity.

I'll add a command line switch for extra URLs.

**Comment by essandess** [comment]
Extra filters are now implemented in the latest commit via the `-x` command line option. Add as many URLs as you like.

Be aware that this refactoring uses regression to downselect the EasyList rule set and produces the most compact and effective PAC file possible. Enormous PAC files and mobile devices don't play well together.

All rules are pooled together, then prioritized with a machine learning algorithm, then downselected.

The existing [proxy.pac](https://raw.githubusercontent.com/essandess/easylist-pac-privoxy/master/proxy.pac) file is **one-tenth** the size of the original EasyList download files, yet is very effective against a wide range of tracker and ad services.
