### ISSUE TITLE
Testing efficacy

### ISSUE THREAD

**Issue by maxcountryman** [essandess/easylist-pac-privoxy#10]
I realize that the .pac packages a subset of the rules, however so far I don't see anything being blocked.

Perhaps a concrete example, which would at least show the rules are working, would be helpful. (For instance, a specific site with known ads that are blocked by the .pac.) Can you suggest anything?

**Comment by essandess** [comment]
The subset blocks the most commonly used adservers and trackers, so if you don't see anything blocked there's some issue.

Do you have a blackhole server running? The `nginx`  configuration in [adblock2privoxy](../../adblock2privoxy) provides one.

OS? Browser?

Test on a desktop. iOS blocking won't work if the blackhole HTTP server isn't returning 200 codes for the blocked sites. There's debugging flags that will work with Chrome to show the blocking actions within a specific page.

**Comment by maxcountryman** [comment]
OS: macOS Mojave (10.14)
Browsers: Safari (12.0), Firefox (62.0.3)

> Test on a desktop

That was my thinking too: I tested with macOS by setting the Automatic Proxy Configuration in the Network Settings to point to the GitHub-hosted proxy.pac. However so far, it doesn't seem like it's having much effect.

A good example of where this clearly isn't working is to load up a site like businessinsider.com or state.com--both have egregious display ads which get through.

> Do you have a blackhole server running?

I haven't tried to set this up yet, I was only trying to plug the proxy.pac in and see how it did.

**Comment by essandess** [comment]
Especially with Safari, I'd start by making sure that you have a blackhole server, and are hosting the `proxy.pac` file on `localhost` using native apache.

Full install commands are part of [macOS-Fortress/readme-and-install.sh](https://github.com/essandess/macOS-Fortress/blob/master/readme-and-install.sh), but it only takes a moment to install and load nginx and start apache. 

After that, make sure that the blackhole address in `http://localhost/proxy.pac` matches your nginx configuration, e.g. `localhost:8119`. And add an adblock2privoxy-based proxy chain to catch all rules.

The full readme-and-install.sh works for me on a fresh macOS install, but I suspect this repo's README.md needs some tweaks to match with the latest Safari browsers.

P.S. This blocks adservers on those sites.
