### ISSUE TITLE
Blocking iOS Updates

### ISSUE THREAD

**Issue by messagehome** [essandess/easylist-pac-privoxy#11]
Is it possible to modify this and have it **block** mesu.apple.com, appldnld.apple.com and gdmf.apple.com?

**Comment by essandess** [comment]
Yes, fork the repo and specify whichever exact domain anchors you want blocked or passed within the initialization of the lists:
```
bad_da_host_exact
good_da_host_exact
```

Make sure that there’s not a conflict in these rules with the logic used in the function `FindProxyForURL ` defined in `proxy.pac.orig`, which calls `EasyListFindProxyForURL` in which all the blocking checks are performed.
