### ISSUE TITLE
breaks many parts of lastest youtube on ios 

### ISSUE THREAD

**Issue by shadowhcf7** [essandess/easylist-pac-privoxy#12]
removes video thumbnails and titles completely

**Comment by essandess** [comment]
> removes video thumbnails and titles completely

All blocking is a consequence of the upstream EasyList/AdBlockPlus rules used.

To override these rules, modify the list `include_these_good_rules` in the script:

https://github.com/essandess/easylist-pac-privoxy/blob/3a2651fc400f6cee44d8f781b46dfc0cd32cb34f/easylist_pac.py#L1672
