### ISSUE TITLE
Appstore

### ISSUE THREAD

**Issue by JuliusBairaktaris** [essandess/easylist-pac-privoxy#14]
When running easylist_pac.py the IOS Appstore gets blocked. Probably there is a whitelist rule needed

**Comment by essandess** [comment]
This shouldn’t happen—the last few commits explicitly allow all connections to Apple specified in https://support.apple.com/en-us/HT210060.

I confirm that have no such issues either on macOS or iOS.

Please update to the latest commit and then please check your `proxy.pac` file to make sure that it’s using the latest rules, which bypass the proxy for these Apple domains and CIDRs. Also, if you’re using a squid proxy, please make sure that `squid.conf` file also has the acl for Apple these destinations.

**Comment by JuliusBairaktaris** [comment]
I just ran the easylist script as it is, and uploaded the Proxy.pac to my github repository. It is a fork of your repository so you can check the proxy.pac on my repo. But I don’t find any blacklist rules for Apple servers but AppStore and Apple Music are blocked.

**Comment by essandess** [comment]
> I just ran the easylist script as it is, and uploaded the Proxy.pac to my github repository. It is a fork of your repository so you can check the proxy.pac on my repo. But I don’t find any blacklist rules for Apple servers but AppStore and Apple Music are blocked.

If this code isn’t in your `proxy.pac` **and** `proxy.pac.orig` then you’ll need to merge upstream and run it again, or troubleshoot why it’s not being added:

https://github.com/essandess/easylist-pac-privoxy/blob/429e49f7dc2e18a7bf92bca09c4d1dd95c2f443f/easylist_pac.py#L684-L732

**Comment by JuliusBairaktaris** [comment]
Oh sorry, the old file was still uploaded. I added the new one

**Comment by JuliusBairaktaris** [comment]
Why did the issue get closed when it didnt get fixed?

**Comment by essandess** [comment]
How is it not fixed?

**Comment by 28439** [comment]
Can confirm that I am having the same issue. I am using the latest easy list_pac.py with those apple domains in that bypass. If I revert back to the easy list_pac.py file from April 3 (commit 3a2651f), I am then able to use the App Store again. I looked through the commit you made after and I still cannot figure out what is causing this.

**Comment by essandess** [comment]
If the PAC file you’re using explicitly goes direct to Apple and bypasses the proxy completely, why is the App Store being blocked?

**Comment by JuliusBairaktaris** [comment]
Well to be honest I also dont know whats causing this issue. Maybe you should investigate it.

**Comment by essandess** [comment]
> Well to be honest I also dont know whats causing this issue. Maybe you should investigate it.

Access to all Apple services including the App store has already been addressed here and in the squid configuration:
https://github.com/essandess/easylist-pac-privoxy/blob/429e49f7dc2e18a7bf92bca09c4d1dd95c2f443f/easylist_pac.py#L684-L732

I cannot replicate the issue and without further information believe that this issue is specific to your own network, configuration, or possibly iOS version.

**Comment by yozzozo** [comment]
@starraiderx @28439 I was running into the App Store not working issue as well, I fixed it by changing the "PROXY localhost:3128" to "DIRECT" at the end of proxy.pac.

This should fix many other issues as well for jailbroken iOS devices using this approach, as critical system services will be able to directly connect instead of being proxied.

**Comment by essandess** [comment]
All those services work fine through a properly configured proxy.

Do you have a proxy running on `localhost:3128`? If not, then that’d be the issue.

**Comment by yozzozo** [comment]
No, on my config (and others who have commented here), it’s a jailbroken
iOS device and there’s no proxy running locally.  The device is setup to
use a PAC file to globally proxy (wifi and cellular) via managed device
profile.

**Comment by essandess** [comment]
If you’re not using a proxy, then just use a simple `proxy.pac.orig` with the flag `--PAC-original`:
```javascript
function FindProxyForURL(url, host)
{
    return "DIRECT";
}
```
