### ISSUE TITLE
"Configure an OpenVPN to use the proxy.pac file hosted on your LAN."

### ISSUE THREAD

**Issue by maxcountryman** [essandess/easylist-pac-privoxy#8]
Can you explain the process for doing this? Cursory Google searches don't yield much.

**Comment by essandess** [comment]
Why, yes!

[macos-openvpn-server](../../macos-openvpn-server)

**Comment by maxcountryman** [comment]
Well yes, I did look at that—it isn’t clear to me how the OpenVPN config consumes the .pac.

**Comment by essandess** [comment]
Just search the repo for "[proxy.pac](https://github.com/essandess/macos-openvpn-server/search?q=proxy.pac&unscoped_q=proxy.pac)".

**Comment by maxcountryman** [comment]
So is it not possible to use the .pac with an OpenVPN client then?

**Comment by essandess** [comment]
It is possible. The link above shows how to configure a client or server push settings do just that.

**Comment by maxcountryman** [comment]
Okay thanks—it seemed like the two configs you linked were for servers exclusively.

Do you mind if I add a note to the README?

**Comment by maxcountryman** [comment]
As far as I can tell, `push "dhcp-option PROXY_AUTO_CONFIG_URL http://192.168.1.1:8080/proxy.pac` **does not** work with OpenVPN client configs. Would be nice if this were mentioned in the documentation.

**Comment by essandess** [comment]
`push` directives belong in server configs because the server pushes the options to the clients.

The client config setting is simply
```
dhcp-option PROXY_AUTO_CONFIG_URL http://192.168.1.1:8080/proxy.pac
```

Both server-pushed and client `dhcp-option` options work.

This is already well-documented in OpenVPN rtfm's.
